import type { Metadata } from "next";
// import Script from 'next/script'
import { Inter } from "next/font/google";
import "./globals.css";
import { TelegramProvider } from "./providers/TelegramBotProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZapchastOl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TelegramProvider>
          {children}
        </TelegramProvider>
      </body>
    </html>
  );
}
