import type { Metadata } from "next";
import Script from 'next/script'
import { Inter } from "next/font/google";
import "./globals.css";
import TelegramBotProvider from "./providers/TelegramBotProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TelegramBotProvider>
        <Script src="https://telegram.org/js/telegram-web-app.js" />
        <body className={inter.className}>{children}</body>
      </TelegramBotProvider>
    </html>
  );
}
